# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multivariate normal density function
#'
#' This function returns the log-density for a multivariate Gaussian distribution.
#' The data must be imputed as a matrix, using e.g., \code{as.matrix}, with each row
#' representing an observation.
#'
#' @param x matrix of observations
#' @param mean mean vector
#' @param sigma positive definite covariance matrix
#' @param logd logical; whether log-density should be returned (default to \code{FALSE})
#' @return density or log-density of the \code{nrow(x)} sample
#' @keywords internal
#' @export
.dmvnorm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call('_mgp_dmvnorm_arma', PACKAGE = 'mgp', x, mean, sigma, logd)
}

#' Distance matrix with geometric anisotropy
#'
#' The function computes the distance between locations, with geometric anisotropy.
#' The parametrization assumes there is a scale parameter, so that \code{scale}
#' is the distortion for the second component only. The angle \code{rho} must lie in
#' \eqn{[-\pi/2, \pi/2]}.
#'
#' @param loc a \code{d} by 2 matrix of locations giving the coordinates of a site per row.
#' @param scale numeric vector of length 1, greater than 1.
#' @param rho angle for the anisotropy, must be larger than \eqn{\pi/2} in modulus.
#' @return a \code{d} by \code{d} square matrix of pairwise distance
#' @export
distg <- function(loc, scale, rho) {
    .Call('_mgp_distg', PACKAGE = 'mgp', loc, scale, rho)
}

